/* IS_AUTOGENERATED_SO_ALLOW_AUTODELETE=YES */
/* The previous line is to allow auto deletion */

#import <Foundation/Foundation.h>
#import <Foundation/NSString.h>
#import "libGolgi.h"


@interface LocationInfo : NSObject
{
    NSString *lat;
    BOOL latIsSet;
    NSString *lon;
    BOOL lonIsSet;
    NSString *time;
    BOOL timeIsSet;
}

@property (readonly) BOOL latIsSet;
- (NSString *)getLat;
- (void)setLat:(NSString *)lat;
@property (readonly) BOOL lonIsSet;
- (NSString *)getLon;
- (void)setLon:(NSString *)lon;
@property (readonly) BOOL timeIsSet;
- (NSString *)getTime;
- (void)setTime:(NSString *)time;

+ (LocationInfo *)deserialiseFromString: (NSString *)string;
+ (LocationInfo *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (LocationInfo *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (LocationInfo *)fromJSONString:(NSString *)jsonString;
+ (LocationInfo *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (LocationInfo *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface autoangel_crashInfo_reqArg : NSObject
{
    LocationInfo *locationInfo;
    BOOL locationInfoIsSet;
    NSString *crashText;
    BOOL crashTextIsSet;
}

@property (readonly) BOOL locationInfoIsSet;
- (LocationInfo *)getLocationInfo;
- (void)setLocationInfo:(LocationInfo *)locationInfo;
@property (readonly) BOOL crashTextIsSet;
- (NSString *)getCrashText;
- (void)setCrashText:(NSString *)crashText;

+ (autoangel_crashInfo_reqArg *)deserialiseFromString: (NSString *)string;
+ (autoangel_crashInfo_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (autoangel_crashInfo_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (autoangel_crashInfo_reqArg *)fromJSONString:(NSString *)jsonString;
+ (autoangel_crashInfo_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (autoangel_crashInfo_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface autoangel_crashInfo_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (autoangel_crashInfo_rspArg *)deserialiseFromString: (NSString *)string;
+ (autoangel_crashInfo_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (autoangel_crashInfo_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (autoangel_crashInfo_rspArg *)fromJSONString:(NSString *)jsonString;
+ (autoangel_crashInfo_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (autoangel_crashInfo_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end
//
// crashInfo
//
@protocol autoangelCrashInfoResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol autoangelCrashInfoResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol autoangelCrashInfoRequestReceiver
- (void)crashInfoWithResultSender:(id<autoangelCrashInfoResultSender>)resultSender andLocationInfo:(LocationInfo *)locationInfo andCrashText:(NSString *)crashText;
@end
@interface autoangelCrashInfoExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

@interface autoangelSvc : NSObject
+ (void)sendCrashInfoUsingResultReceiver:(id<autoangelCrashInfoResultReceiver>)resultReceiver andDestination:(NSString *)_dst withLocationInfo:(LocationInfo *)locationInfo andCrashText:(NSString *)crashText;
+ (void)sendCrashInfoUsingResultReceiver:(id<autoangelCrashInfoResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withLocationInfo:(LocationInfo *)locationInfo andCrashText:(NSString *)crashText;
+ (void)sendCrashInfoUsingResultHandler:(void (^)(autoangelCrashInfoExceptionBundle *))resultHandler andDestination:(NSString *)_dst withLocationInfo:(LocationInfo *)locationInfo andCrashText:(NSString *)crashText;
+ (void)sendCrashInfoUsingResultHandler:(void (^)(autoangelCrashInfoExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withLocationInfo:(LocationInfo *)locationInfo andCrashText:(NSString *)crashText;
+ (void)httpSendCrashInfoUsingResultHandler:(void (^)(autoangelCrashInfoExceptionBundle *))resultHandler andDestination:(NSString *)_dst withLocationInfo:(LocationInfo *)locationInfo andCrashText:(NSString *)crashText;
+ (void)sendCrashInfoUsingResultReceiver:(id<autoangelCrashInfoResultReceiver>)resultReceiver orResultHandler:(void (^)(autoangelCrashInfoExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withLocationInfo:(LocationInfo *)locationInfo andCrashText:(NSString *)crashText;
+ (void)registerCrashInfoRequestReceiver:(id<autoangelCrashInfoRequestReceiver>)requestReceiver;
+ (void)registerCrashInfoRequestHandler:(void (^)(id<autoangelCrashInfoResultSender> resultSender, LocationInfo * locationInfo, NSString * crashText))requestHandler;

@end

@interface Temp : NSObject
{
    NSInteger value;
    BOOL valueIsSet;
}

@property (readonly) BOOL valueIsSet;
- (NSInteger)getValue;
- (void)setValue:(NSInteger )value;

+ (Temp *)deserialiseFromString: (NSString *)string;
+ (Temp *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (Temp *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (Temp *)fromJSONString:(NSString *)jsonString;
+ (Temp *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (Temp *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface Led : NSObject
{
    NSInteger value;
    BOOL valueIsSet;
}

@property (readonly) BOOL valueIsSet;
- (NSInteger)getValue;
- (void)setValue:(NSInteger )value;

+ (Led *)deserialiseFromString: (NSString *)string;
+ (Led *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (Led *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (Led *)fromJSONString:(NSString *)jsonString;
+ (Led *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (Led *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface Demo_setLed_reqArg : NSObject
{
    Led *led;
    BOOL ledIsSet;
}

@property (readonly) BOOL ledIsSet;
- (Led *)getLed;
- (void)setLed:(Led *)led;

+ (Demo_setLed_reqArg *)deserialiseFromString: (NSString *)string;
+ (Demo_setLed_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (Demo_setLed_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (Demo_setLed_reqArg *)fromJSONString:(NSString *)jsonString;
+ (Demo_setLed_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (Demo_setLed_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface Demo_setLed_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (Demo_setLed_rspArg *)deserialiseFromString: (NSString *)string;
+ (Demo_setLed_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (Demo_setLed_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (Demo_setLed_rspArg *)fromJSONString:(NSString *)jsonString;
+ (Demo_setLed_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (Demo_setLed_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface Demo_setThermostatTemp_reqArg : NSObject
{
    Temp *temp;
    BOOL tempIsSet;
}

@property (readonly) BOOL tempIsSet;
- (Temp *)getTemp;
- (void)setTemp:(Temp *)temp;

+ (Demo_setThermostatTemp_reqArg *)deserialiseFromString: (NSString *)string;
+ (Demo_setThermostatTemp_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (Demo_setThermostatTemp_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (Demo_setThermostatTemp_reqArg *)fromJSONString:(NSString *)jsonString;
+ (Demo_setThermostatTemp_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (Demo_setThermostatTemp_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface Demo_setThermostatTemp_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (Demo_setThermostatTemp_rspArg *)deserialiseFromString: (NSString *)string;
+ (Demo_setThermostatTemp_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (Demo_setThermostatTemp_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (Demo_setThermostatTemp_rspArg *)fromJSONString:(NSString *)jsonString;
+ (Demo_setThermostatTemp_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (Demo_setThermostatTemp_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface Demo_reportTemp_reqArg : NSObject
{
    Temp *temp;
    BOOL tempIsSet;
}

@property (readonly) BOOL tempIsSet;
- (Temp *)getTemp;
- (void)setTemp:(Temp *)temp;

+ (Demo_reportTemp_reqArg *)deserialiseFromString: (NSString *)string;
+ (Demo_reportTemp_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (Demo_reportTemp_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (Demo_reportTemp_reqArg *)fromJSONString:(NSString *)jsonString;
+ (Demo_reportTemp_reqArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (Demo_reportTemp_reqArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end

@interface Demo_reportTemp_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (Demo_reportTemp_rspArg *)deserialiseFromString: (NSString *)string;
+ (Demo_reportTemp_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
+ (Demo_reportTemp_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject;
+ (Demo_reportTemp_rspArg *)fromJSONString:(NSString *)jsonString;
+ (Demo_reportTemp_rspArg *)fromJSONObject:(GolgiJSONObject *)jsonObject error:(GolgiJSONError **)err;
+ (Demo_reportTemp_rspArg *)fromJSONString:(NSString *)jsonString error:(GolgiJSONError **)err;
- (NSString *)toJSON;
- (id)initWithIsSet:(BOOL)defIsSet;
@end
//
// setLed
//
@protocol DemoSetLedResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol DemoSetLedResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol DemoSetLedRequestReceiver
- (void)setLedWithResultSender:(id<DemoSetLedResultSender>)resultSender andLed:(Led *)led;
@end
@interface DemoSetLedExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// setThermostatTemp
//
@protocol DemoSetThermostatTempResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol DemoSetThermostatTempResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol DemoSetThermostatTempRequestReceiver
- (void)setThermostatTempWithResultSender:(id<DemoSetThermostatTempResultSender>)resultSender andTemp:(Temp *)temp;
@end
@interface DemoSetThermostatTempExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

//
// reportTemp
//
@protocol DemoReportTempResultSender
- (NSString *)getRequestSenderId;
- (void)success;
@end
@protocol DemoReportTempResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol DemoReportTempRequestReceiver
- (void)reportTempWithResultSender:(id<DemoReportTempResultSender>)resultSender andTemp:(Temp *)temp;
@end
@interface DemoReportTempExceptionBundle: NSObject
{
    GolgiException * golgiException;
}
@property GolgiException * golgiException;
@end

@interface DemoSvc : NSObject
+ (void)sendSetLedUsingResultReceiver:(id<DemoSetLedResultReceiver>)resultReceiver andDestination:(NSString *)_dst withLed:(Led *)led;
+ (void)sendSetLedUsingResultReceiver:(id<DemoSetLedResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withLed:(Led *)led;
+ (void)sendSetLedUsingResultHandler:(void (^)(DemoSetLedExceptionBundle *))resultHandler andDestination:(NSString *)_dst withLed:(Led *)led;
+ (void)sendSetLedUsingResultHandler:(void (^)(DemoSetLedExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withLed:(Led *)led;
+ (void)httpSendSetLedUsingResultHandler:(void (^)(DemoSetLedExceptionBundle *))resultHandler andDestination:(NSString *)_dst withLed:(Led *)led;
+ (void)sendSetLedUsingResultReceiver:(id<DemoSetLedResultReceiver>)resultReceiver orResultHandler:(void (^)(DemoSetLedExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withLed:(Led *)led;
+ (void)registerSetLedRequestReceiver:(id<DemoSetLedRequestReceiver>)requestReceiver;
+ (void)registerSetLedRequestHandler:(void (^)(id<DemoSetLedResultSender> resultSender, Led * led))requestHandler;

+ (void)sendSetThermostatTempUsingResultReceiver:(id<DemoSetThermostatTempResultReceiver>)resultReceiver andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)sendSetThermostatTempUsingResultReceiver:(id<DemoSetThermostatTempResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)sendSetThermostatTempUsingResultHandler:(void (^)(DemoSetThermostatTempExceptionBundle *))resultHandler andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)sendSetThermostatTempUsingResultHandler:(void (^)(DemoSetThermostatTempExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)httpSendSetThermostatTempUsingResultHandler:(void (^)(DemoSetThermostatTempExceptionBundle *))resultHandler andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)sendSetThermostatTempUsingResultReceiver:(id<DemoSetThermostatTempResultReceiver>)resultReceiver orResultHandler:(void (^)(DemoSetThermostatTempExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)registerSetThermostatTempRequestReceiver:(id<DemoSetThermostatTempRequestReceiver>)requestReceiver;
+ (void)registerSetThermostatTempRequestHandler:(void (^)(id<DemoSetThermostatTempResultSender> resultSender, Temp * temp))requestHandler;

+ (void)sendReportTempUsingResultReceiver:(id<DemoReportTempResultReceiver>)resultReceiver andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)sendReportTempUsingResultReceiver:(id<DemoReportTempResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)sendReportTempUsingResultHandler:(void (^)(DemoReportTempExceptionBundle *))resultHandler andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)sendReportTempUsingResultHandler:(void (^)(DemoReportTempExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)httpSendReportTempUsingResultHandler:(void (^)(DemoReportTempExceptionBundle *))resultHandler andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)sendReportTempUsingResultReceiver:(id<DemoReportTempResultReceiver>)resultReceiver orResultHandler:(void (^)(DemoReportTempExceptionBundle *))resultHandler withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTemp:(Temp *)temp;
+ (void)registerReportTempRequestReceiver:(id<DemoReportTempRequestReceiver>)requestReceiver;
+ (void)registerReportTempRequestHandler:(void (^)(id<DemoReportTempResultSender> resultSender, Temp * temp))requestHandler;

@end
